### ISSUE TITLE
RequestContext is missing from RouterEvent

### ISSUE THREAD

**Issue by tszebeni** [Giftbit/cassava#4]
`APIGatewayProxyEvent` contains an attribute `requestContext` with type `APIGatewayEventRequestContext` which is not copied over in method `proxyEventToRouterEvent`. This way lambda cannot use authorizer details like user claims it was invoked by.
It is easy to extend the `Router` by overloading its method `proxyEventToRouterEvent` but the problem is that the method marked with modifier `private` instead `protected` so a ts-ignore directive is needed.

**Comment by pushplay** [comment]
Thanks for the report.  I'll look into it.

**Comment by pushplay** [comment]
Fixed in https://github.com/Giftbit/cassava/releases/tag/v2.4.1
